### ISSUE TITLE
Connection issue

### ISSUE THREAD

**Issue by jbehura** [seisman/FnetPy#4]
Hi,

Would you happen to have any insight into the following error?

requests.exceptions.SSLError: HTTPSConnectionPool(host='www.fnet.bosai.go.jp', port=443): Max retries exceeded with url: /auth/dataget/cgi-bin/dataget.cgi (Caused by SSLError(SSLError(1, '[SSL: DH_KEY_TOO_SMALL] dh key too small (_ssl.c:1131)')))

Cheers,
Jyoti

**Comment by seisman** [comment]
I also have the same problem. I still don't have a clue why it happens and how to fix it. I think it may be working for macOS + Python 3.6-3.9, but doesn't works on latest Linux distros and Python 3.10

**Comment by seisman** [comment]
The connection issue should be fixed in commit 5d6feab2e201079d08f120156fd359d9c29393d2
